package(default_visibility = ["//visibility:public"])
load("//kern_interp:buildvars.bzl", "COPTS")
exports_files(["tri240.txt","tri570.txt","tri1032.txt","tri1614.txt","tri2344.txt",
  "tri3206.txt","tri4192.txt","tri5322.txt","tri6544.txt","tri7970.txt","tri9496.txt",
  "tri11146.txt","tri12944.txt","tri14870.txt","tri16912.txt","tri19126.txt","tri21424.txt",
  "tri23898.txt","tri26504.txt","tri29214.txt","tri32056.txt","tri35074.txt","tri38184.txt",
  "tri41458.txt","tri44832.txt","tri48370.txt","tri52016.txt","tri55802.txt","tri59744.txt",
  "tri63810.txt","tri67976.txt","tri72322.txt","tri76736.txt","tri81370.txt"])
