package(default_visibility = ["//visibility:public"])
load("//kern_interp:buildvars.bzl", "COPTS")
exports_files(["sphere_240_faces.txt",
"sphere_570_faces.txt",
"sphere_1032_faces.txt",
"sphere_1614_faces.txt",
"sphere_2344_faces.txt", "sphere_3206_faces.txt", 
  "sphere_4192_faces.txt", "sphere_5322_faces.txt", "sphere_6544_faces.txt", 
  "sphere_7970_faces.txt", "sphere_9496_faces.txt", "sphere_11146_faces.txt", 
  "sphere_12944_faces.txt", "sphere_14870_faces.txt", "sphere_16912_faces.txt",
   "sphere_19126_faces.txt", "sphere_21424_faces.txt", "sphere_23898_faces.txt",
    "sphere_26504_faces.txt", "sphere_29214_faces.txt", "sphere_32056_faces.txt",
     "sphere_35074_faces.txt", "sphere_38184_faces.txt", "sphere_41458_faces.txt",
      "sphere_44832_faces.txt", "sphere_48370_faces.txt", "sphere_52016_faces.txt", 
      "sphere_55802_faces.txt", "sphere_59744_faces.txt", "sphere_63810_faces.txt", 
      "sphere_67976_faces.txt", "sphere_72322_faces.txt", "sphere_76736_faces.txt", 
      "sphere_81370_faces.txt","sphere_86096_faces.txt","sphere_90938_faces.txt","sphere_95944_faces.txt","sphere_101070_faces.txt",])


